### PR TITLE
Add GitHub Action for publishing on PyPI

### PR DESCRIPTION
**Pull request by nforro**

### CODE REVIEW

**Comment by nforro** [comment]
Now we need to set the `PYPI_API_TOKEN` secret, I don't have the permissions to do that.

**Comment by junaruga** [comment]
Thanks! Now I updated your permission as OWNER of the rpm-py-installer. Can you get it?

Now please still don't tag the new version yet. I have things to do before the release.

As I said I want to upgrade setup.py and I also actually am reviving the CentOS 6 case using https://vault.centos.org/6.10/ on CI now.

**Comment by junaruga** [comment]
Ah I see. It was a permission of this GitHub repository. Just moment. I will take a look at it.

**Comment by nforro** [comment]
> As I said I want to upgrade setup.py and I also actually am reviving the CentOS 6 case using https://vault.centos.org/6.10/ on CI now.

Don't worry, I won't.

**Comment by junaruga** [comment]
I created the token from https://pypi.org/manage/project/rpm-py-installer/settings/ - API tokens - "Create a token for rpm-py-installer". Then I did set it on Settings - Secrets - Actions - Repository secrets.

**Comment by nforro** [comment]
Ok, thanks, that should be enough for this action to work.

**Review by junaruga — APPROVED** [review]
Thanks! Feel free to merge it!

**Pull request merged**
