### PR TITLE
Create MANIFEST.in

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
I havent included the docs.  Up to you, if you want to add that.

**Comment by junaruga** [comment]
@jayvdb what is the file `MANIFEST.in`?
Is it a file related to Python implementation?

**Comment by junaruga** [comment]
It looks the file is something related to Python. :)
https://docs.python.org/3/distutils/sourcedist.html
Let me see it later.
Thanks for the pull-request!

**Comment by jayvdb** [comment]
when you run `python setup.py sdist` , this file is used to determine what extra bits are included in the sdist.

In this case, you do not want to be releasing a wheel using `bdist_wheel`, because that bypasses `setup.py`, so the `sdist` needs to be kept small.  Which is why I didnt include the docs.

But LICENSE and tests are small and necessary for packaging.  They are more important than the README.md

**Comment by junaruga** [comment]
I cherry-picked this PR's commit to modify it.
https://github.com/junaruga/rpm-py-installer/pull/180

I did not include the test files in the tar.gz files.
Because its' to reduce the file size, and I think not including tests files is a trend for the some packages like `pip`, `wheel`, and Ruby on Rails and etc.

> https://src.fedoraproject.org/rpms/python-pip/blob/master/f/python-pip.spec#_74

python-pip.spec

```
# to get tests:
# git clone https://github.com/pypa/pip && cd pip
# git checkout $VERSION && tar -czvf ../pip-$VERSION-tests.tar.gz tests/
%if %{with tests}
Source1:        pip-%{version}-tests.tar.gz
%endif
...

%prep
...
tar -xf %{SOURCE1}
...
```

Ruby on Rails.
https://src.fedoraproject.org/rpms/rubygem-activerecord/blob/master/f/rubygem-activerecord.spec#_15

So, in case of rpm-py-installer.spec, that could be like this.

```
# git clone https://github.com/junaruga/rpm-py-installer.git && cd rpm-py-installer
# git checkout $VERSION && rpm-py-installer-$VERSION-tests.tar.gz tests/
Source1:        rpm-py-installer-%{version}-tests.tar.gz
```

**Comment by junaruga** [comment]
Close this PR as it was merged by https://github.com/junaruga/rpm-py-installer/pull/180 .
Thank you for your PR, @jayvdb !

**Comment by jayvdb** [comment]
A wheel should *always* excludes tests, *because* it is not the sdist.  I don't have the resources to investigate your theory that this is a new trend at RedHat for Python and Ruby, but it definitely isnt the case at OpenSUSE , where they expect tests in the same tarball as the code unless there are extreme circumstances justifying special treatment.  This repo has a tiny tiny test suite - the size of the sdist is inconsequential.

**Comment by junaruga** [comment]
@jayvdb I can understand your situation. The size of the sdist is inconsequential.

### Suggestioin

I suppose the reason you resist not including the test files is you do not want to create the additional `Source1` in your `python-rpm-py-installer.spec` for each version bump, right?

If it's like that, I would suggest adding below way that once you set below code in the spec file, you do not have to update the code for each version bump.

```
Source1: https://github.com/junaruga/rpm-py-installer/archive/v%{version}.tar.gz

tar xzvf %{SOURCE1} rpm-py-installer-%{version}/tests
tar xzvf %{SOURCE1} rpm-py-installer-%{version}/test-requirements.txt
```

## My focus

By the way, current file size under the `tests` directory is 616KB.

```
$ du -sh tests/
616K	tests/
```

My focusing points are
* `rpm-py-installer`' user's experiences are always prioritized than the developer's experiences.
* Scalablity and flexibility.

Right now "the size of the sdist is inconsequential".
But in the future the file size might be much bigger.

For example now I am trying to create CentOS5 environment ( https://github.com/junaruga/rpm-py-installer/pull/171#issuecomment-480320272 ). But I might be able to have to install OpenSSL, curl, Python's source code in this repository, because there is a SSL connection issue on old version's OpenSSL, and addtional softwares that need to built with the new OpenSSL.
I want to consider the possibility to support embedded use case or small sized Linux situations such as [AlpineLinux](https://alpinelinux.org/) and BusyBox [BusyBox](https://www.busybox.net/) for the future. In those world, the file size is more important.

### Cases not to include testing files in an upstream package or have own testing archive file in the RPM spec file

> A wheel should always excludes tests, because it is not the sdist. I don't have the resources to investigate your theory that this is a new trend at RedHat for Python and Ruby, but it definitely isnt the case at OpenSUSE

This is just my impression. I have a chance to work with 100+ RubyGems packages.
And it's not a trend at Red Hat, but at upstream RubyGems packages.
As a result, the RPM package, the downstream RPM spec files had to manage the own test archive.

For example, here is the case of `nokogiri` (RPM package name: `rubygem-nokogiri`).
https://github.com/sparklemotion/nokogiri/issues/1855
> There was a public discussion on the mailing list and in a couple of different github issues about removing specs from the gem, and was met with general approval from users and downstream library maintainers.

Here is the example on Fedora RPM packages.
You can see all the RPM spec files by below commands.

```
$ curl -OL http://src.fedoraproject.org/repo/rpm-specs-latest.tar.xz

$ tar xvf rpm-specs-latest.tar.xz

$ grep -E '\-(test|tests|spec).(tar.gz|tgz)$' rpm-specs/*.spec | wc -l
86

$ grep -E '(test|tests|spec).(tar.gz|tgz)$' rpm-specs/*.spec | wc -l
rpm-specs/cryptlib.spec:Source4:    https://crypto-bone.com/fedora/cryptlib-tests.tar.gz
rpm-specs/docbook-slides.spec:Source4: %{name}-tests.tar.gz
rpm-specs/fail2ban.spec:#Source0: https://github.com/sebres/%{name}/archive/f2b-perfom-prepare-716-cs.tar.gz#/%{name}-test.tar.gz
rpm-specs/lua.spec:Source3:        http://www.lua.org/tests/lua-%{test_version}-tests.tar.gz
rpm-specs/python-pip.spec:Source1:        pip-%{version}-tests.tar.gz
rpm-specs/rubygem-actioncable.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-actionmailer.spec:Source1: actionmailer-%{version}-tests.tgz
rpm-specs/rubygem-actionpack.spec:Source1: actionpack-%{version}-tests.tgz
rpm-specs/rubygem-actionview.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-activejob.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-activemodel-serializers-xml.spec:Source1: activemodel-serialization-xml-%{version}-tests.tgz
rpm-specs/rubygem-activemodel.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-activerecord.spec:Source1: activerecord-%{version}-tests.tgz
rpm-specs/rubygem-activeresource.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-activestorage.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-activesupport.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-ancestry.spec:Source1: %{name}-%{version}-test.tar.gz
rpm-specs/rubygem-arel.spec:Source1: arel-%{version}-tests.tgz
rpm-specs/rubygem-bootsnap.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-capybara.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-CFPropertyList.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-closure-compiler.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-codemirror-rails.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-coderay.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-coffee-rails.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-compass-core.spec:Source1: rubygem-compass-core-tests.tgz
rpm-specs/rubygem-cucumber-core.spec:Source1: %{name}-%{version}-spec.tar.gz
rpm-specs/rubygem-cucumber.spec:Source1: %{name}-%{version}-spec.tar.gz
rpm-specs/rubygem-dalli.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-database_cleaner.spec:Source2: %{gem_name}-%{version}-tests.tar.gz
rpm-specs/rubygem-delayed_job_active_record.spec:Source1: delayed_job_active_record-%{version}-tests.tgz
rpm-specs/rubygem-delorean.spec:Source1:  %{name}-%{version}-spec.tgz
rpm-specs/rubygem-ejs.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-execjs.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-fakefs.spec:Source1: fakefs-%{version}-tests.tgz
rpm-specs/rubygem-faraday.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-ffi.spec:Source1: %{gem_name}-%{version}-spec.tgz
rpm-specs/rubygem-gem2rpm.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-globalid.spec:Source1: %{gem_name}-%{version}-tests.tar.gz
rpm-specs/rubygem-guard-shell.spec:Source1: %{name}-%{version}-spec.tar.gz
rpm-specs/rubygem-guard.spec:Source1: %{name}-%{version}-spec.tar.gz
rpm-specs/rubygem-haml.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-hike.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-hiredis.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-jekyll.spec:Source1:        %{gem_name}-%{version}-test.tar.gz
rpm-specs/rubygem-json-schema.spec:Source1:        %{name}-%{version}-test.tgz
rpm-specs/rubygem-listen.spec:Source1: rubygem-listen-%{version}-tests.tgz
rpm-specs/rubygem-mini_magick.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-multi_json.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-multipart.spec:Source1: %{gem_name}-tests.tgz
rpm-specs/rubygem-notiffany.spec:Source1: rubygem-notiffany-0.1.1-spec.tar.gz
rpm-specs/rubygem-omniauth.spec:Source1: omniauth-1.3.1-tests.tgz
rpm-specs/rubygem-parallel.spec:Source1:        %{gem_name}-%{version}-spec.tar.gz
rpm-specs/rubygem-parseconfig.spec:Source1:		rubygem-parseconfig-%{version}-tests.tar.gz
rpm-specs/rubygem-pdf-inspector.spec:Source1: pdf-inspector-%{version}-spec.tgz
rpm-specs/rubygem-pdf-reader.spec:Source1: pdf-reader-%{version}-spec.tgz
rpm-specs/rubygem-puma.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-rack-cache.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-rack-protection.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-rack-test.spec:Source1: %{gem_name}-%{version}-spec.tgz
rpm-specs/rubygem-rails_warden.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-railties.spec:Source1: railties-%{version}-tests.tgz
rpm-specs/rubygem-rainbow.spec:Source1: rainbow-%{version}-tests.tgz
rpm-specs/rubygem-rake-contrib.spec:Source1: %{gem_name}-tests.tar.gz
rpm-specs/rubygem-rake.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-rbvmomi.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-recaptcha.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-ref.spec:Source1: ref-%{version}-tests.tgz
rpm-specs/rubygem-responders.spec:Source1:        %{name}-%{version}-test.tgz
rpm-specs/rubygem-rspec-rails.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-rugged.spec:Source1:       %{gem_name}-%{version}-test.tgz
rpm-specs/rubygem-sass-rails.spec:Source1: sass-rails-%{version}-tests.tgz
rpm-specs/rubygem-sass.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-sinatra.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-spring.spec:Source1: rubygem-%{gem_name}-%{version}-tests.tar.gz
rpm-specs/rubygem-sprockets-rails.spec:Source1: sprockets-rails-%{version}-tests.tgz
rpm-specs/rubygem-sprockets.spec:Source1: sprockets-%{version}-tests.tgz
rpm-specs/rubygem-syntax.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-thin.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-thor.spec:Source1: %{gem_name}-%{version}-spec.tar.gz
rpm-specs/rubygem-tomlrb.spec:Source1:        %{gem_name}-%{version}-test.tar.gz
rpm-specs/rubygem-uglifier.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-web-console.spec:Source1: %{gem_name}-%{version}-tests.tgz
rpm-specs/rubygem-websocket-driver.spec:Source1: websocket-driver-ruby-%{version}-tests.tgz
rpm-specs/rubygem-xml-simple.spec:Source1: %{gem_name}-tests.tar.gz
rpm-specs/swift-lang.spec:Source4:        https://github.com/apple/swift-integration-tests/archive/swift-%{swifttag}.tar.gz#/swift-integration-tests.tar.gz
```

**Comment by junaruga** [comment]
By the way, I wanted to included your commit hash information and your name respecting the PR, when I merge it to the master branch. But when I did merge with squash option in another PR, your name's commit hash was replaced wrongly. That's my fault. Sorry for that.
Thank you for your PR. I really appreciate it.

**Comment by jayvdb** [comment]
Dont worry - I am glad my name was removed.  The patch you merged is basically useless.  `LICENSE` is automatically included by the latest setuptools, `test-requirements.txt` and `tests` are not included, so explicitly excluding them is a nop.  Including a README is of dubious benefit.  Almost nobody reads them on the disk, and they are mostly full of unhelpful information for distro users, like how to install, when `rpm -qi ..` already provides the info users need.

You can exclude all of the gems from your `-tests` grep - there is a long standing problem which is causing that shift in gem packaging.  See https://github.com/rubygems/rubygems/issues/735 for more details.

Then you are left with only special cases.

Thanks for pointing out http://src.fedoraproject.org/repo/rpm-specs-latest.tar.xz - that is very helpful for easy investigations of redhat specs.

> .. AlpineLinux and BusyBox ..

AlpineLinux builds packages and removes all of the garbage.  They also want tests in the sdist.  I dont know about BusyBox, but I expect it is the same.

The reluctance is in having two Source for one library.  I have tried the approach you mentioned, and the openSUSE maintainers told me to switch to only using GitHub archives if the sdist didnt include the tests.

Using github archives slows down my batch updating because I get the auto-notification of new releases from pypi, and need to check the sdist from pypi first, and then also fetch the archive from github to verify the relevant files are the same as the sdist (they are different way too often).  I usually skip any github sources, and do them in a separate batch when I have more time to hand-hold the scripts. 

The .rpm test data under `tests/` wont be used by other distros, so you could exclude them from the manifest and then add them as a separate tarball in the fedora .spec .

Then
```
$ du -s tests
92      tests
```

The valid tarballs can be generated by the test suite - they dont need to be shipped.  Probably the invalid tarballs too.  With those also gone.
```
> du -s tests
76      tests
```

;-)

**Comment by junaruga** [comment]
> The reluctance is in having two Source for one library. I have tried the approach you mentioned, and the openSUSE maintainers told me to switch to only using GitHub archives if the sdist didnt include the tests.

I think that's a good idea.
Only using GitHub archives, for a notification from the GitHub release, using Antiya (See below) is a possible workflow.

Right now I like to use 
* An archive on PyPI: Pipeline for users.
* An archive on GitHub: Pipleline for developers including downstream packagers.

> Using github archives slows down my batch updating because I get the auto-notification of new releases from pypi, and need to check the sdist from pypi first, and then also fetch the archive from github to verify the relevant files are the same as the sdist (they are different way too often). I usually skip any github sources, and do them in a separate batch when I have more time to hand-hold the scripts.

My release flow, upload the released archive to pypi at first, then test by myself (15 minutes), then push git tag to the repository. This time could be very short time.

Sure. you are using the notification from pypi.
Do you know a notification service Anitya? This enables monitoring GitHub.

https://stackoverflow.com/questions/17395151/how-can-i-subscribe-to-updates-of-a-package-on-pypi#18559594

Here is a page for rpm.
rpm
https://release-monitoring.org/project/15204/

I just created a page for rpm-py-installer
python-rpm-py-installer
https://release-monitoring.org/project/19546/
You can edit it too.

> The .rpm test data under tests/ wont be used by other distros, so you could exclude them from the manifest and then add them as a separate tarball in the fedora .spec .

Possibly yes. We might be able to skip the tests using "The .rpm test data".
We need to check the code how those are used in the tests.

**Pull request closed without merging**
